"use client";

import { useState, useEffect } from "react";
import { FaSignOutAlt, FaDownload, FaCopy, FaTrash, FaChevronDown, FaChevronUp, FaCrown, FaLock } from "react-icons/fa";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "motion/react";
import toast from "react-hot-toast";
import { jsPDF } from "jspdf";

// ─── Utility: Sanitize JD into a clean paragraph ───
function cleanJobDescription(raw) {
    if (!raw) return "";
    return raw
        .replace(/\r\n/g, "\n")
        .replace(/\n{2,}/g, "\n")
        .replace(/\n/g, " ")
        .replace(/\s{2,}/g, " ")
        .replace(/\t/g, " ")
        .trim();
}

// ─── PDF Generator ───
function downloadPdf(letterText, index) {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    const lineHeight = 7;
    let y = margin + 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(letterText, usableWidth);

    for (const line of lines) {
        if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
        }
        doc.text(line, margin, y);
        y += lineHeight;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(160);
    doc.text("Generated by CovGen", margin, doc.internal.pageSize.getHeight() - 10);

    doc.save(`cover-letter-${index + 1}.pdf`);
}

// ─── Skeleton Card ───
function SkeletonCard() {
    return (
        <div className="bg-white rounded-3xl p-6 border border-slate-200/60 shadow-sm animate-pulse">
            <div className="flex items-center justify-between mb-4">
                <div className="h-4 bg-slate-200 rounded-full w-24" />
                <div className="h-5 bg-slate-200 rounded-full w-16" />
            </div>
            <div className="space-y-3 mb-6">
                <div className="h-3 bg-slate-200 rounded w-full" />
                <div className="h-3 bg-slate-200 rounded w-5/6" />
                <div className="h-3 bg-slate-200 rounded w-4/6" />
                <div className="h-3 bg-slate-200 rounded w-3/6" />
            </div>
            <div className="flex items-center gap-2">
                <div className="h-8 bg-slate-200 rounded-xl w-20" />
                <div className="h-8 bg-slate-200 rounded-xl w-20" />
                <div className="h-8 bg-slate-200 rounded-xl w-20" />
            </div>
        </div>
    );
}

// ─── Letter Card Component ───
function SavedLetterCard({ letter, index, userPlan, onDelete }) {
    const [showJd, setShowJd] = useState(false);
    const [deleting, setDeleting] = useState(false);
    const [confirmDelete, setConfirmDelete] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(letter.generatedText);
        toast.success("Copied to clipboard!");
    };

    const handleDownload = () => {
        if (userPlan !== "pro") {
            toast("Upgrade to Pro to download PDFs", {
                icon: "🔒",
                style: {
                    border: "1px solid #f59e0b",
                    padding: "12px 16px",
                    color: "#92400e",
                    background: "#fffbeb",
                    fontWeight: "600",
                },
            });
            return;
        }
        downloadPdf(letter.generatedText, index);
        toast.success("PDF downloaded!");
    };

    const handleDelete = async () => {
        if (!confirmDelete) {
            setConfirmDelete(true);
            setTimeout(() => setConfirmDelete(false), 3000);
            return;
        }
        setDeleting(true);
        try {
            const token = localStorage.getItem("token");
            const res = await fetch(
                `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/coverletters/${letter._id}`,
                {
                    method: "DELETE",
                    headers: { Authorization: `Bearer ${token}` },
                }
            );
            if (res.ok) {
                toast.success("Letter deleted");
                onDelete(letter._id);
            } else {
                toast.error("Failed to delete");
            }
        } catch {
            toast.error("Network error");
        } finally {
            setDeleting(false);
            setConfirmDelete(false);
        }
    };

    const expiryHours = letter.expiresIn;
    const expiryLabel = expiryHours !== null && expiryHours !== undefined
        ? expiryHours > 24
            ? `${Math.ceil(expiryHours / 24)}d left`
            : expiryHours > 0
                ? `${expiryHours}h left`
                : "Expiring soon"
        : null;

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            transition={{ duration: 0.3, delay: index * 0.05 }}
            layout
            className="group bg-white rounded-3xl p-6 border border-slate-200/60 shadow-[0_4px_24px_rgba(0,0,0,0.04)] hover:shadow-[0_8px_40px_rgba(59,130,246,0.08)] hover:border-blue-200/60 transition-all duration-300"
        >
            {/* Header */}
            <div className="flex items-start justify-between mb-4">
                <div>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-blue-500">
                        {letter.modelUsed || "AI Generated"}
                    </span>
                    <p className="text-xs text-slate-400 mt-1">
                        {new Date(letter.createdAt).toLocaleDateString("en-US", {
                            month: "short", day: "numeric", year: "numeric",
                        })} • {new Date(letter.createdAt).toLocaleTimeString("en-US", {
                            hour: "2-digit", minute: "2-digit",
                        })}
                    </p>
                </div>
                <div className="flex items-center gap-2">
                    {expiryLabel && (
                        <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-amber-50 text-amber-600 border border-amber-100">
                            ⏳ {expiryLabel}
                        </span>
                    )}
                    {letter.plan === "pro" && (
                        <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-purple-50 text-purple-600 border border-purple-100 flex items-center gap-1">
                            <FaCrown className="w-2.5 h-2.5" /> Pro
                        </span>
                    )}
                </div>
            </div>

            {/* Letter preview */}
            <div className="mb-4">
                <p className="text-sm text-slate-700 leading-relaxed line-clamp-5">
                    {letter.generatedText}
                </p>
            </div>

            {/* JD Toggle */}
            <button
                onClick={() => setShowJd(!showJd)}
                className="w-full flex items-center justify-between px-4 py-2.5 rounded-xl bg-slate-50 hover:bg-slate-100 border border-slate-200/60 text-xs font-semibold text-slate-500 transition-all duration-200 mb-4 cursor-pointer"
            >
                <span>📋 View Job Description</span>
                {showJd ? <FaChevronUp className="w-3 h-3" /> : <FaChevronDown className="w-3 h-3" />}
            </button>

            <AnimatePresence>
                {showJd && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.25 }}
                        className="overflow-hidden mb-4"
                    >
                        <div className="p-4 bg-slate-50 rounded-xl border border-slate-200/60 text-sm text-slate-600 leading-relaxed max-h-40 overflow-y-auto"
                            style={{ scrollbarWidth: "thin" }}
                        >
                            {cleanJobDescription(letter.jobDescription)}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Action Buttons */}
            <div className="flex items-center gap-2 pt-2 border-t border-slate-100">
                <button
                    onClick={handleCopy}
                    className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-100 transition-all duration-200 active:scale-95 cursor-pointer"
                >
                    <FaCopy className="w-3 h-3" /> Copy
                </button>
                <button
                    onClick={handleDownload}
                    className={`flex-1 flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all duration-200 active:scale-95 cursor-pointer border ${
                        userPlan === "pro"
                            ? "bg-emerald-50 text-emerald-600 hover:bg-emerald-100 border-emerald-100"
                            : "bg-slate-50 text-slate-400 border-slate-200 cursor-not-allowed"
                    }`}
                >
                    {userPlan === "pro" ? (
                        <><FaDownload className="w-3 h-3" /> PDF</>
                    ) : (
                        <><FaLock className="w-3 h-3" /> PDF</>
                    )}
                </button>
                <button
                    onClick={handleDelete}
                    disabled={deleting}
                    className={`flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold transition-all duration-200 active:scale-95 cursor-pointer border ${
                        confirmDelete
                            ? "bg-red-500 text-white border-red-500 hover:bg-red-600"
                            : "bg-red-50 text-red-500 hover:bg-red-100 border-red-100"
                    } ${deleting ? "opacity-50 cursor-not-allowed" : ""}`}
                >
                    <FaTrash className="w-3 h-3" />
                    {confirmDelete ? "Sure?" : ""}
                </button>
            </div>
        </motion.div>
    );
}

// ─── Main Profile Component ───
export default function Profile() {
    const router = useRouter();
    const [user, setUser] = useState(null);
    const [letters, setLetters] = useState([]);
    const [loading, setLoading] = useState(true);
    const [letterLoading, setLetterLoading] = useState(true);
    const [resumeLink, setResumeLink] = useState("");
    const [customInstr, setCustomInstr] = useState("");
    const [saving, setSaving] = useState(false);
    const [hasChanges, setHasChanges] = useState(false);
    const [origResumeLink, setOrigResumeLink] = useState("");
    const [origCustomInstr, setOrigCustomInstr] = useState("");

    // Load user from localStorage
    useEffect(() => {
        const savedUser = localStorage.getItem("user");
        if (savedUser) {
            try {
                const userData = JSON.parse(savedUser);
                setUser(userData);
                setResumeLink(userData.resumeLink || "");
                setCustomInstr(userData.customInstructions || "");
                setOrigResumeLink(userData.resumeLink || "");
                setOrigCustomInstr(userData.customInstructions || "");
            } catch (e) {
                console.error("Error parsing user data", e);
            }
        }
        setLoading(false);
    }, []);

    // Fetch saved cover letters
    useEffect(() => {
        const fetchLetters = async () => {
            try {
                const token = localStorage.getItem("token");
                if (!token) return;
                const res = await fetch(
                    `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/coverletters`,
                    { headers: { Authorization: `Bearer ${token}` } }
                );
                if (res.ok) {
                    const data = await res.json();
                    setLetters(data.letters || []);
                }
            } catch (err) {
                console.error("Failed to fetch letters", err);
            } finally {
                setLetterLoading(false);
            }
        };
        fetchLetters();
    }, []);

    const handleLogout = () => {
        localStorage.removeItem("token");
        localStorage.removeItem("user");
        document.cookie = "token=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; SameSite=Lax";
        window.location.href = "/";
    };

    const handleDeleteLetter = (id) => {
        setLetters((prev) => prev.filter((l) => l._id !== id));
    };

    // Track changes
    const profileChanged = resumeLink !== origResumeLink || customInstr !== origCustomInstr;

    const handleSaveProfile = async () => {
        setSaving(true);
        try {
            const token = localStorage.getItem("token");
            const res = await fetch(
                `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/users/onboarding`,
                {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        Authorization: `Bearer ${token}`,
                    },
                    body: JSON.stringify({ resumeLink, customInstructions: customInstr }),
                }
            );
            const data = await res.json();
            if (res.ok) {
                toast.success("Profile updated!");
                // Sync localStorage
                const savedUser = localStorage.getItem("user");
                if (savedUser) {
                    const userObj = JSON.parse(savedUser);
                    userObj.resumeLink = resumeLink;
                    userObj.customInstructions = customInstr;
                    localStorage.setItem("user", JSON.stringify(userObj));
                    setUser(userObj);
                    window.dispatchEvent(new Event("userUpdated"));
                }
                setOrigResumeLink(resumeLink);
                setOrigCustomInstr(customInstr);
            } else {
                toast.error(data.message || "Failed to update");
            }
        } catch {
            toast.error("Network error");
        } finally {
            setSaving(false);
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500" />
            </div>
        );
    }

    if (!user) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center">
                    <p className="text-slate-500 mb-4">Please log in to view your profile.</p>
                    <button
                        onClick={() => router.push("/auth")}
                        className="px-6 py-2.5 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-xl font-bold shadow-lg"
                    >
                        Sign In
                    </button>
                </div>
            </div>
        );
    }

    return (
        <main className="min-h-screen bg-[#FAFBFF] px-4 py-24 md:px-10 relative overflow-hidden">
            {/* Background Orbs */}
            <div className="absolute top-0 left-0 w-full h-[400px] bg-gradient-to-b from-blue-50/60 to-transparent -z-[1] pointer-events-none" />
            <div className="absolute w-[500px] h-[500px] bg-blue-400/8 rounded-full blur-[80px] -top-40 -left-40 pointer-events-none" />
            <div className="absolute w-[400px] h-[400px] bg-purple-400/8 rounded-full blur-[80px] top-1/4 -right-40 pointer-events-none" />

            {/* ═══ Profile Hero Card ═══ */}
            <motion.section
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="max-w-5xl mx-auto mb-10 relative"
            >
                {/* Gradient Banner */}
                <div className="h-32 md:h-40 rounded-t-3xl bg-gradient-to-r from-blue-500 via-purple-500 to-blue-600 relative overflow-hidden">
                    <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9InJnYmEoMjU1LDI1NSwyNTUsMC4wNSkiPjxwYXRoIGQ9Ik0zNiAxOGMtNi42MjcgMC0xMiA1LjM3My0xMiAxMnM1LjM3MyAxMiAxMiAxMiAxMi01LjM3MyAxMi0xMi01LjM3My0xMi0xMi0xMnptMCAxOGMtMy4zMTQgMC02LTIuNjg2LTYtNnMyLjY4Ni02IDYtNiA2IDIuNjg2IDYgNi0yLjY4NiA2LTYgNnoiLz48L2c+PC9nPjwvc3ZnPg==')] opacity-30" />
                </div>

                {/* Profile Content */}
                <div className="bg-white rounded-b-3xl border border-slate-200/60 border-t-0 shadow-[0_8px_40px_rgba(0,0,0,0.04)] px-6 md:px-10 pb-8 pt-0 relative">
                    {/* Avatar */}
                    <div className="flex flex-col md:flex-row items-center md:items-end gap-4 -mt-14 md:-mt-16">
                        {user.picture ? (
                            <div className="relative">
                                <div className="w-28 h-28 md:w-32 md:h-32 rounded-2xl overflow-hidden border-4 border-white shadow-xl ring-2 ring-blue-500/20">
                                    <Image
                                        src={user.picture}
                                        alt="Profile"
                                        width={128}
                                        height={128}
                                        className="w-full h-full object-cover"
                                    />
                                </div>
                            </div>
                        ) : (
                            <div className="w-28 h-28 md:w-32 md:h-32 rounded-2xl bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center text-white text-4xl font-bold border-4 border-white shadow-xl ring-2 ring-blue-500/20">
                                {user.name?.charAt(0) || "U"}
                            </div>
                        )}

                        <div className="flex-1 text-center md:text-left pb-2">
                            <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
                                <div>
                                    <h1
                                        className="text-2xl md:text-3xl font-bold text-slate-900"
                                        style={{ fontFamily: "Space Grotesk, sans-serif" }}
                                    >
                                        {user.name}
                                    </h1>
                                    <p className="text-slate-500 text-sm mt-0.5">{user.email}</p>
                                </div>
                                <div className="flex items-center gap-3 justify-center md:justify-end">
                                    <span
                                        className={`inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full text-xs font-bold border shadow-sm ${
                                            user.plan === "pro"
                                                ? "bg-gradient-to-r from-purple-50 to-blue-50 text-purple-700 border-purple-200"
                                                : "bg-slate-50 text-slate-600 border-slate-200"
                                        }`}
                                    >
                                        {user.plan === "pro" ? (
                                            <><FaCrown className="w-3 h-3 text-yellow-500" /> Pro Plan</>
                                        ) : (
                                            "Free Plan"
                                        )}
                                    </span>
                                    <button
                                        onClick={handleLogout}
                                        className="inline-flex items-center gap-2 px-4 py-1.5 bg-red-50 text-red-500 hover:bg-red-100 border border-red-100 rounded-full text-xs font-semibold transition-colors cursor-pointer"
                                    >
                                        <FaSignOutAlt className="w-3 h-3" />
                                        Logout
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Stats Row */}
                    <div className="grid grid-cols-2 gap-4 mt-8">
                        <div className="bg-slate-50/80 rounded-2xl p-4 text-center border border-slate-100">
                            <p className="text-2xl font-black text-blue-600">{user.credits}</p>
                            <p className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mt-1">Credits</p>
                        </div>
                        <div className="bg-slate-50/80 rounded-2xl p-4 text-center border border-slate-100">
                            <p className="text-2xl font-black text-purple-600">{letterLoading ? "—" : letters.length}</p>
                            <p className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider mt-1">Saved Letters</p>
                        </div>
                    </div>

                    {/* Editable Fields */}
                    <div className="space-y-5 mt-8">
                        <div>
                            <div className="flex justify-between mb-2">
                                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider">Resume Link</label>
                                <span className="text-xs text-slate-400">{resumeLink?.length || 0}/500</span>
                            </div>
                            <input
                                type="url"
                                value={resumeLink}
                                maxLength={500}
                                onChange={(e) => setResumeLink(e.target.value)}
                                placeholder="https://drive.google.com/your-resume"
                                className="w-full px-4 py-3 rounded-xl bg-slate-50/80 border border-slate-200 text-sm text-slate-700 outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 transition-all placeholder:text-slate-300"
                            />
                        </div>

                        <div>
                            <div className="flex justify-between mb-2">
                                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider">Default Instructions</label>
                                <span className="text-xs text-slate-400">{customInstr?.length || 0}/10000</span>
                            </div>
                            <textarea
                                value={customInstr}
                                maxLength={10000}
                                onChange={(e) => setCustomInstr(e.target.value)}
                                placeholder="Tell the AI about yourself — your skills, experience, tone preferences..."
                                rows={4}
                                className="w-full px-4 py-3 rounded-xl bg-slate-50/80 border border-slate-200 text-sm text-slate-700 outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 transition-all resize-y min-h-[80px] placeholder:text-slate-300"
                                style={{ scrollbarWidth: "thin" }}
                            />
                        </div>

                        {profileChanged && (
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                className="flex items-center gap-3"
                            >
                                <button
                                    onClick={handleSaveProfile}
                                    disabled={saving}
                                    className="px-6 py-2.5 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-xl font-bold text-sm shadow-lg shadow-blue-500/20 hover:shadow-blue-500/30 hover:scale-[1.02] transition-all active:scale-95 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer"
                                >
                                    {saving ? "Saving..." : "Save Changes"}
                                </button>
                                <button
                                    onClick={() => { setResumeLink(origResumeLink); setCustomInstr(origCustomInstr); }}
                                    className="px-4 py-2.5 text-sm font-semibold text-slate-500 hover:text-slate-700 hover:bg-slate-100 rounded-xl transition-all cursor-pointer"
                                >
                                    Discard
                                </button>
                            </motion.div>
                        )}
                    </div>
                </div>
            </motion.section>

            {/* ═══ Saved Cover Letters ═══ */}
            <section className="max-w-5xl mx-auto">
                <motion.div
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="flex items-center justify-between mb-6"
                >
                    <div>
                        <h2
                            className="text-2xl md:text-3xl font-bold text-slate-900"
                            style={{ fontFamily: "Space Grotesk, sans-serif" }}
                        >
                            📄 Saved Cover Letters
                        </h2>
                        <p className="text-sm text-slate-400 mt-1">
                            {user.plan === "free"
                                ? "Free plan letters auto-delete after 3 days"
                                : "Your letters are saved permanently"}
                        </p>
                    </div>
                </motion.div>

                {letterLoading ? (
                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <SkeletonCard />
                        <SkeletonCard />
                        <SkeletonCard />
                    </div>
                ) : letters.length === 0 ? (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="py-20 text-center bg-white/60 backdrop-blur-xl border-2 border-dashed border-slate-200 rounded-3xl shadow-sm"
                    >
                        <div className="w-20 h-20 bg-blue-50 rounded-full flex items-center justify-center mx-auto mb-6 shadow-inner">
                            <span className="text-4xl">📝</span>
                        </div>
                        <h3 className="text-2xl font-bold mb-2 text-slate-800" style={{ fontFamily: "Space Grotesk, sans-serif" }}>
                            No saved cover letters yet
                        </h3>
                        <p className="text-slate-400 mb-8 max-w-sm mx-auto">
                            Head to the Dashboard and generate your first cover letter. It&apos;ll show up here automatically!
                        </p>
                        <motion.button
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            onClick={() => router.push("/dashboard")}
                            className="px-8 py-3.5 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-full font-extrabold shadow-[0_10px_20px_rgba(59,130,246,0.3)] hover:shadow-[0_15px_30px_rgba(59,130,246,0.4)] transition-all cursor-pointer"
                        >
                            Go to Dashboard
                        </motion.button>
                    </motion.div>
                ) : (
                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                        <AnimatePresence mode="popLayout">
                            {letters.map((letter, idx) => (
                                <SavedLetterCard
                                    key={letter._id}
                                    letter={letter}
                                    index={idx}
                                    userPlan={user.plan}
                                    onDelete={handleDeleteLetter}
                                />
                            ))}
                        </AnimatePresence>
                    </div>
                )}
            </section>

            <footer className="mt-16 text-center text-sm text-slate-400">
                Built with ❤️ by Samaresh
            </footer>
        </main>
    );
}
